### PR TITLE
GEN png icons from svg files

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by raveit65** [comment]
Why always Portuguese language failed to build for some distros (fedora, debian)?
```
make[3]: *** [Makefile:604: pt/pt.stamp] Error 1
```

**Comment by raveit65** [comment]
@yetist 
Such a command to fix travis build belongs in `before_scripts:` part of travis.yml ?
```
# disable pt language for help in search tool
sed -i s/"IGNORE_HELP_LINGUAS ="/"IGNORE_HELP_LINGUAS = pt"/g gsearchtool/help/Makefile.am
```

**Comment by raveit65** [comment]
@rbuj 
I found an unexpected new file with a weird directory :)
```
rpmbuild/BUILDROOT/mate-utils-1.22.1-1.fc30.x86_64/usr/share/icons/shot.png/shot.png/shot.png
```
I only created a new tarball from PR branch to test changes.

**Comment by raveit65** [comment]
Wow, in the 7 attempt the build runs fine for fedora at travis.

**Comment by yetist** [comment]
@raveit65 

yes, put the command in before_scripts can works.

**Comment by raveit65** [comment]
Good, travis commit works well, i will pick him to master.

**Comment by raveit65** [comment]
```
make[6]: rsvg-convert: Command not found
```
librsvg2-tools seems to be missing in travis config for fedora.

**Comment by raveit65** [comment]
In all travis builds.
```
/bin/bash: inkscape: command not found
```

**Comment by raveit65** [comment]
@rbuj 
Thanks, `/usr/share/icons/shot.png/shot.png/shot.png` won't be installed anymore.
Can you please add a dependency check for `rsvg-convert`?
Same like you did here https://github.com/mate-desktop/mate-desktop/commit/d83bccb64d612034be471c0724edd129519c3584#diff-67e997bcfdac55191033d57a16d1408aR231

**Comment by alexarnaud** [comment]
> Seems to work fine, I get the icons for mate-system-log and mate-disk-usage-analyzer in the menu, and both programs open fine

What is the goal of this PR? I'm just asking because I'm and others visual-impaired are concerned about big icon sizer that SVG usually can provide.

Best regards,
Alex.

**Comment by raveit65** [comment]
> What is the goal of this PR?

Why not testing PR?
And take a look at icon in about-dialog.

**Comment by alexarnaud** [comment]
> > What is the goal of this PR?
> 
> Why not testing PR?
> And take a look at icon in about-dialog.

You're totally right to ask me to do that but it's not as simple as asking that. Compiling require a little bit of effort and to be honest I prefer to keep my energy to do things I'm useful in (especially in a11y).

See this thread to see why I need too many energy to support what developers do... https://gitlab.gnome.org/GNOME/gtk/issues/1739

Also IMHO a PR should be understandable without to have to compile it.

Best regards,
Alex.

**Comment by raveit65** [comment]
It improves/sharpen the icons in about-dialogs of applications, no more and no less.
And installing a PR helps always understanding what a PR does ;)

Don't worry nobody from team wants to break accessibility support :)
... i am only speaking for MATE.

**Comment by alexarnaud** [comment]
> It improves/sharpen the icons in about-dialogs of applications, no more and no less.

OK, thanks for the explanation.

> And installing a PR helps always understanding what a PR does ;)

Indeed.

> Don't worry, nobody from team wants to break accessibility support :)
> ... i am only speaking for MATE.

:), I know you're concerned about that and I'm very thankful about that.

Best regards,
Alex.

**Pull request merged**
