### PR TITLE
Follow the FSF guidelines for license and copyright notices

### PR DESCRIPTION
**Pull request by rbuj**
- Use always the same code snippet for including the top-level config.h

### CODE REVIEW

**Review by lukefromdc — APPROVED** [review]
This is fine by me, probably hasn't been updated in a long time. A completed test build just proved there are no build-breaking typos in all those files

**Comment by raveit65** [comment]
Should we not add our copyright to all the files?
`Copyright (C) 20012-2021 MATE Developers`
I am not sure if that name makes sense for a lawer,
so i am fine with actual state of PR.

Btw. i am not sure if it is correct to remove the fsf address.
```
- * You should have received a copy of the GNU Library General Public
- * License along with this library; if not, write to the
 -* Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
- * Boston, MA 02110-1301, USA.
+ * You should have received a copy of the GNU General Public License
+ * along with MATE Utils.  If not, see <https://www.gnu.org/licenses/>.
```

**Comment by rbuj** [comment]
"How to use GNU licenses for your own software" - "The license notices"
https://www.gnu.org/licenses/gpl-howto.html.en

>     Foobar is free software: you can redistribute it and/or modify
>     it under the terms of the GNU General Public License as published by
>     the Free Software Foundation, either version 3 of the License, or
>     (at your option) any later version.
> 
>     Foobar is distributed in the hope that it will be useful,
>     but WITHOUT ANY WARRANTY; without even the implied warranty of
>     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
>     GNU General Public License for more details.
> 
>     You should have received a copy of the GNU General Public License
>     along with Foobar.  If not, see <https://www.gnu.org/licenses/>.

To use a different set of GPL versions, you would modify the end of the first long paragraph. For instance, to license under version 2 or later, you would replace “3” with “2”.

**Review by raveit65 — APPROVED** [review]
LGTM

**Pull request merged**
