### PR TITLE
Add MATE Disk Image Mounter utility

### PR DESCRIPTION
**Pull request by rbuj**
Based on https://github.com/GNOME/gnome-disk-utility/commit/2794ee121829d656d460da58c0ecaa84271e6fe7

### CODE REVIEW

**Comment by rbuj** [comment]
@raveit65 I think that the warning message has been removed from the build log.

**Comment by monsta** [comment]
Maybe it should be a Caja extension instead?

**Comment by raveit65** [comment]
> Maybe it should be a Caja extension instead?

Really?
Than mate-disk-usage-analyzer can be moved to caja too, because of the same logic?

I don't see that a caja-extension use a binary under /usr/bin/ .

**Comment by vkareh** [comment]
@raveit65 did the build warning go away for you after the last push?

**Comment by raveit65** [comment]
@vkareh 
yes, you can check it for yourself at travis(ci) :)
old build with warning: 
https://travis-ci.org/mate-desktop/mate-utils/jobs/586448274#L4264
last build without warning:
https://travis-ci.org/mate-desktop/mate-utils/jobs/591555995#L4227

**Pull request merged**
