### PR TITLE
baobab: Fix conversion warnings (-Wconversion)

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by raveit65** [comment]
Where do you see the warnings (build log) ?

**Comment by rbuj** [comment]
> Where do you see the warnings (build log) ?

I saw the warnings on a local build log called make.log
```
#!/bin/bash
export LANG=en_US.UFT-8

NPROC=`nproc`
CFLAGS="-march=native -mtune=native -fomit-frame-pointer -malign-double -fstrict-aliasing -ffast-math -Wconversion -Wunused-macros -Wunused-parameter"
CONF="--prefix=/usr --enable-compile-warnings=maximum --enable-cxx-warnings=maximum --disable-debug"
CFLAGS="${CFLAGS}" ./autogen.sh ${CONF} &> conf.log && make -j${NPROC} &> make.log && sudo make install &> /dev/null
```

**Review by raveit65 — APPROVED** [review]
It seems OK,
warnings are gone and `mate-disk-usage-analyzer `starts well.

**Review by lukefromdc — APPROVED** [review]
Build completes fine, warnings (w my normal build options) now limited to deprecations and some "no previous prototype" warnings. Build binary rain in place fine in place of the one in my mate-utils install.

Looks like a decent cleanup of some old code problems here

**Pull request merged**
