### PR TITLE
[mate-dictionary] Add scroll tabs with mouse wheel

### PR DESCRIPTION
**Pull request by tamplan**
Add scroll tabs with mouse wheel for mate-dictionary's dialog

### CODE REVIEW

**Comment by tamplan** [comment]
I see there are 2 commits here, should I wait until the first PR is validated and merged before doing another PR even if they are on two different branches?

**Comment by raveit65** [comment]
It's Ok, when first commit only remove trailing whitespaces

**Comment by raveit65** [comment]
We have a file conflict.

**Comment by raveit65** [comment]
Looks like this is caused by merging `Remove trailing whitespaces` commit.

**Comment by raveit65** [comment]
Yeap, conflict is solved. I start testing.

**Comment by sc0w** [comment]
@tamplan  can you remove the merge commit? (third commit)

**Comment by tamplan** [comment]
> @tamplan can you remove the merge commit? (third commit)
> 
> I mean, it can be squashed into other

I have no trace of merge commit in my local repository.
What is the command to revert a merge commit online?

Thanks for any help on this by advance.

**Comment by raveit65** [comment]
@sc0w 
`git rebase master` should remove the merge commit in your local repo.
This is what i do always...

**Comment by raveit65** [comment]
@tamplan 
I don't have the merge commit locally, no action is needed.

**Comment by sc0w** [comment]
I see no changes of first commit in this PR (Remove trailing whitespaces), I don't understand why, it is reverted with commit "Merge branch 'master' into notebook" ?

**Comment by tamplan** [comment]
I remember what i have done here and perhaps i know why we have a commit mentioned "Merge branch 'master' into notebook".

I resolve the file conflict online and have got <<<< notebook some code and >>>> master, i remove **<<<< notebook** and **>>>> master** online, nothing else.

**Comment by sc0w** [comment]
I reviewed some files locally with this PR and the changes 'Remove trailing whitespaces' are applied, but I don't understad why github don't show us the changes into the "Files changed" tab.

**Comment by sc0w** [comment]
ah, I got it

That commit is already in master

so, all the commits here can be squashed into one

**Comment by sc0w** [comment]
@tamplan 

I think this must work

```
git clone https://github.com/tamplan/mate-utils
cd mate-utils
git checkout notebook
git reset --hard 34505eb
git rebase master
git cherry-pick 9d4f0af
git push -f
```

**Comment by raveit65** [comment]
rebase+ merge button
and one commit in master
https://github.com/mate-desktop/mate-utils/commits/master
which is the same like
```
git checkout master
git pull
git checkout -b tamplan-notebook master
git pull https://github.com/tamplan/mate-utils.git notebook
git rebase master
```

**Pull request merged**
