### PR TITLE
avoid deprecated 'g_type_class_add_private'

### PR DESCRIPTION
**Pull request by sc0w**

### CODE REVIEW

**Comment by raveit65** [comment]
Was log-viewer tested?
```
[rave@mother ~]$ mate-system-log 

(mate-system-log:9954): Gtk-CRITICAL **: 10:41:42.448: gtk_toolbar_insert: assertion 'GTK_IS_TOOLBAR (toolbar)' failed

(mate-system-log:9954): Gtk-CRITICAL **: 10:41:42.448: gtk_toolbar_insert: assertion 'GTK_IS_TOOLBAR (toolbar)' failed
```

**Comment by raveit65** [comment]
`logview-findbar-avoid-g_type_class_add_private` is the first commit which breaks the start of log-viewer.

**Comment by raveit65** [comment]
Not related to PR, it happens with master branch too.
Executing the `filter` preference window gives me this warning.
```
[rave@mother ~]$ mate-system-log 

(mate-system-log:25774): Gtk-WARNING **: 12:42:16.176: gtk_window_set_titlebar() called on a realized window
```

**Comment by raveit65** [comment]
Ok, it seems that the other commits for log-viewer are good and doesn't cause the segfault.
Beside from that i am still wondering why the authentication window which starts the log-viewer is gtk2 ?

**Comment by raveit65** [comment]
Mate-search-tool failed to start!
```
[rave@mother ~]$ mate-search-tool 
**
GLib-GObject:ERROR:../gobject/gobject.c:1813:g_object_new_internal: assertion failed: (nqueue != NULL)
Aborted (core dumped)
```

It seems that mate-dictionary and mate-disk-usage-analyzer are running fine in a quick test.

**Comment by sc0w** [comment]
@raveit65 please review again

**Comment by raveit65** [comment]
Mate-system-log rans fine now, i see only Gtk warnings in terminal which are already in master branch.
```
[rave@mother ~]$ mate-system-log 

(mate-system-log:25109): Gtk-WARNING **: 11:14:26.282: gtk_window_set_titlebar() called on a realized window

(mate-system-log:25109): Gtk-WARNING **: 11:15:28.113: Negative content width -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkToggleButton)

(mate-system-log:25109): Gtk-WARNING **: 11:15:28.113: Negative content height -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkToggleButton)
```
Last ones was from search-bar, they are not related to PR.
Mate-search-tool runs fine too.

**Comment by raveit65** [comment]
This is working here.
Bildschirmfoto zu 2019-08-30 09-05-28

**Comment by lukefromdc** [comment]
The dictionary applet worked here until very recently, and I ruled out glib 2.61.2 by reverting (though I did not rebuild against the older version). Some recent change in Debian Unstable (or maybe my panel build?)  must be to blame for the applet issue, in which the icon lights up when clicked but no dictionary window opens. Has nothing to do with this PR and we have another tester reporting the applet works.

**Comment by lukefromdc** [comment]
Should I go ahead and merge this or wait for anothr review? We have a heck of a lot of open PR's right now, this one came from one core team member and has been approved by two others.

**Comment by sc0w** [comment]
For me this PR is safe and ready to merge

I will work in more mate components with the same deprecated function

**Pull request merged**
