### PR TITLE
Add screenshot support for HiDPI displays

### PR DESCRIPTION
**Pull request by vkareh**
* Pointer coordinates needed scaling to show up in the correct location.
* Window borders needed scaling to avoid a memory overflow when redrawing it.
* Monitor dimensions needed scaling to show the correct size, as well as support for multi-monitor masking.

Monitor masking is when you have multiple monitors with different sizes, and take a screenshot of the entire desktop.
I am not currently able to test this last feature.

### CODE REVIEW

**Comment by lukefromdc** [comment]
Even with two (small, mismatched) monitors I could not reproduce any issues with master and getting the whole desktop in a screenshot

**Comment by raveit65** [comment]
Width/HeightOfScreen implementaition is affected, should be reviewed by @sc0w too.

**Comment by vkareh** [comment]
@sc0w - on other toolkits (i.e. Qt), a value of 0 means that it's auto-scaled. This is not the case for GTK+, but I'm guarding against it ever being the case. You're right that it's not necessary, though, and I can remove it if it makes more sense that way.

I can do a separate batch of PRs to address that

**Comment by monsta** [comment]
In case the mentioned check would actually be necessary, it should be placed before you divide something by `scale` - we wouldn't want to divide by zero... :slightly_smiling_face:

**Pull request merged**
