### PR TITLE
Fix -Werror=cast-function-type with GCC 8

### PR DESCRIPTION
**Pull request by rbuj**
```shell
export CFLAGS="-Werror=cast-function-type -Wno-deprecated-declarations"
./autogen.sh --prefix=/usr
make
sudo make install
```

### CODE REVIEW

**Comment by sc0w** [comment]
travis fails in fedora:

```
Traceback (most recent call last):
  File "/usr/bin/itstool", line 1611, in <module>
    doc.merge_translations(translations, opts.lang, strict=opts.strict)
  File "/usr/bin/itstool", line 999, in merge_translations
    lcnode.setProp(attr, origlang)
  File "/usr/lib64/python3.7/site-packages/libxml2.py", line 3588, in setProp
    if ret is None:raise treeError('xmlSetProp() failed')
libxml2.treeError: xmlSetProp() failed
make[3]: *** [Makefile:602: pt/pt.stamp] Error 1
make[3]: Leaving directory '/rootdir/gsearchtool/help'
make[2]: *** [Makefile:443: all-recursive] Error 1
make[2]: Leaving directory '/rootdir/gsearchtool'
make[1]: *** [Makefile:511: all-recursive] Error 1
make[1]: Leaving directory '/rootdir'
make: *** [Makefile:443: all] Error 2
!!! ERROR: run command [docker exec -t mate-utils-fedora-build /rootdir/src_build].
The command "./docker-build --name ${DISTRO} --verbose --config .travis.yml --build autotools" exited with 1.
```

**Comment by raveit65** [comment]
> travis fails in fedora:

Known issue 
https://github.com/mate-desktop/mate-utils/issues/210
https://github.com/itstool/itstool/issues/36
This can happen randomly with every language.
And it is possible that this error will be gone if you start build again.

**Comment by raveit65** [comment]
Now, the build passed :)

**Comment by lukefromdc** [comment]
Build with
export CFLAGS="-Werror=cast-function-type -Wno-deprecated-declarations"
also completed fine

**Pull request merged**
