### PR TITLE
baobab-chart: avoid deprecated 'gtk_style_context_set_background'

### PR DESCRIPTION
**Pull request by sc0w**

### CODE REVIEW

**Comment by raveit65** [comment]
Still wondering why it is save to remove this function?
....and because it works isn't an answer :)

**Comment by lukefromdc** [comment]
This means according to GtkInspector, the window background (in most theme the theme background color) is what one would expect to see here unless something in the code is changing it to the white I am actually seeing. Question is what is doing that with gtk_style_context_set_background removed. Anything else with css I would expect to show up in GtkInspector.

**Comment by sc0w** [comment]
@raveit65 

> Still wondering why it is save to remove this function?

I don't know

With deprecated functions that must affect the look, I frist test removing the functions to see exactly what part of the look are affected, and, if the look seems to be the same, I open the PR.

> It seems to work in a quick runtime test,
> but i really like to know why it is save to remove this functions.

Safe to merge? I don't know, anyway, this can be reverted easily, and replaced with alternative solutions if it makes problems.

**Comment by sc0w** [comment]
I have tested `mate-utils 1.8.1` in `mate 1.8.1 (gtk 2)` and the background color of the widget is the same (white #FFFFFF) like master and here

This PR is safe to merge for me

**Comment by raveit65** [comment]
So it was completely wrong from previous developer to write this code here?
Btw, he wrote useless code?
Anyway, maybe this was needed with old css theming (<3.20), feel free to merge it if you're sure.

**Comment by sc0w** [comment]
@raveit65 

> So it was completely wrong from previous developer to write this code here?
> Btw, he wrote useless code?

I don't know why that code is there, but seems to do nothing.

**Pull request merged**
