### PR TITLE
Fix spelling and grammar mistakes

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by sc0w** [comment]
I think **grey** and **gray** is the same, why not **grey** ?

**Comment by rbuj** [comment]
> I think **grey** and **gray** is the same, why not **grey** ?

Grey and gray are two different spellings of the same word.
Gray is more common in American English.

**Comment by raveit65** [comment]
Also present in 1.20 branch due to a cherry-pick.

Thanks a lot.

**Comment by rbuj** [comment]
I did the spelling & grammar revision using LanguageTool:

$ java -Dfile.encoding=UTF-8 -jar ~/Documents/LanguageTool-4.2/languagetool-commandline.jar -l en-US -d EN_QUOTES,WHITESPACE_RULE,PUNCTUATION_PARAGRAPH_END,COMMA_PARENTHESIS_WHITESPACE --xmlfilter index.docbook

**Pull request merged**
