### PR TITLE
Remove init_stock_icons code and replace gtk_drag_set_icon_stock with gtk_drag_set_icon_name

### PR DESCRIPTION
**Pull request by zhuyaliang**
Use the icons provided in the system's local theme.

### CODE REVIEW

**Review by lukefromdc — APPROVED** [review]
Didn't notice any changes in icon behavior in mate-screenshot or mate-search-tool with this installed. One less deprecation, simpler code, behavior seems same as master

**Comment by cwendling** [comment]
Not tested, but probably good. But the commit message is incorrect, it's the other way around (*replace gtk_drag_set_icon_stock() with gtk_drag_set_icon_name()*)

**Comment by zhuyaliang** [comment]
@cwendling Fixed

**Review by raveit65 — APPROVED** [review]
LGTM,
runs well and all icons are there.

**Comment by zhuyaliang** [comment]
@raveit65 Need to manually set ```mate-search-tool``` keyboard shortcuts

**Pull request merged**
