### PR TITLE
avoid deprecated gdk_screen_get_active_window

### PR DESCRIPTION
**Pull request by sc0w**
make new function taken from:

https://git.gnome.org/browse/gtk+/commit/?id=6b9e481e38571f73237f6b8a38cb4bc6987bc4ca

with little changes adapted to work in screenshot-utils.c

**the tests:** take screenshot of the current window, and if you like to see possible warnings, you can test in a terminal with `mate-screenshot -w`

### CODE REVIEW

**Comment by monsta** [comment]
That's because `XGetWindowProperty` uses different values for the first two arguments here.
In the original commit `x11_screen->xdisplay` and `x11_screen->xroot_window` were used, so `x11_screen` variable was actually used and didn't cause a build warning.

**Comment by sc0w** [comment]
@raveit65 
weird, tested again and I saw no build warnings, anyway yes, the var is unused, commit rebased

@monsta 
> That's because XGetWindowProperty uses different values for the first two arguments here.
> In the original commit x11_screen->xdisplay and x11_screen->xroot_window were used, so x11_screen variable was actually used and didn't cause a build warning.

yes, I changed that to work here in the file screenshot-utils.c

please test again, unused var deleted

**Comment by raveit65** [comment]
> weird, tested again and I saw no build warnings, anyway yes, the var is unused, commit rebased

Some warning are depending on compiler options.
I saw that with using 'mock' build server for rpms.

**Comment by raveit65** [comment]
@sc0w 
I don't know if all options are needed but this command makes those and other warnings visible.
```
./autogen.sh CFLAGS="-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic" && make
```

**Comment by raveit65** [comment]
warning is gone :-)

**Comment by raveit65** [comment]
@monsta 
Why not pushing this if  2 other persons approved this before you?
Or do you expect that someone other , let's say clem or stephano will review this too?
...lol

**Comment by raveit65** [comment]
merged
https://github.com/mate-desktop/mate-utils/commit/9a5f07e008367db8676586551e71357443a2aa21

**Pull request closed without merging**
