### PR TITLE
Gtk3 fixes

### PR DESCRIPTION
**Pull request by oz123**
This branch enables a new UI and OLD UI (file format ONLY, no visual changes...) so one can compile and *run* with both GTK+ versions.

### CODE REVIEW

**Comment by raveit65** [comment]
Looks like this PR have the changes from the other too?

**Comment by raveit65** [comment]
Are you able to rebase the PR ?
'Modify glade file for the new glade format' is obsolete by other glade commits.
So they can squash in one commit.
If not we can do that.

**Comment by raveit65** [comment]
Also the gdk_device_grab/ungrab and gdk_window_get_display is deprecated with gtk+-3.20.
See here for an example to use gdk_seat_.........
https://github.com/mate-desktop/mate-screensaver/pull/97/commits/63e9ed1a9dff175858d895f5db15a82614900054#diff-5af3270290564a3d2b60ee6d06ed53fdL302
..... but only if you want to do it right ;)

PS: i'm currently testing the PR

**Comment by raveit65** [comment]
Hmm, i see 'new-glade' in window decoration.
bildschirmfoto zu 2016-06-19 13-10-48

**Comment by oz123** [comment]
Sorry, I needed some easy method to see that correct file is loaded... I removed it now.

**Comment by oz123** [comment]
As for deprecation in GTK+3.20, I am currently using GTK+3.18. I will correct GTK+3.20 deprecations  later.

**Comment by oz123** [comment]
Yes, this branch is based on the program version Branch. It's not so clean, but again, I needed some way to know I am using the correct version...

**Comment by raveit65** [comment]
Np, we can rebase the brach before merging.
Thank you

**Comment by raveit65** [comment]
Well, we can fix the gtk+-3.20 deprecation later after merging.

**Comment by oz123** [comment]
There are still some deprecated stuff, but at this point, I will stop pushing more changes. 
Shall I do the rebase?

**Comment by raveit65** [comment]
Yeah, a rebase would be nice.

**Comment by oz123** [comment]
@raveit65, OK, I rebased. I am sorry I only managed to narrow it to 5 commits which makes sense.
As for the version feature I made another request, but it is completely separate from this PR.

**Comment by raveit65** [comment]
Opps, can you please remove the deprecated GtkStock stuff.
Using Stock icons for buttons and menus is one of the main Look&Feel in Mate desktop.
So we decided to use them until they were droped in gtk+.
There are some Stock icons which are save to replace, ie. stock warning or question,
as they are not use for buttons or menus.
Unfortunately this isn't a single commit.
https://github.com/mate-desktop/mate-utils/pull/152/commits/c089b27a55f175fc04a2ddb8c4bb03086806c52f#diff-8507404f8bb6f00f4840b46593da1b46R598
Thank you

**Comment by oz123** [comment]
You mean I should revert the removal of GtkStock icons?

**Comment by raveit65** [comment]
Yes, but i can do that with a rebase before merging.

**Comment by oz123** [comment]
OK, so before I add more unintended stuff, go ahead with the rebase and merge. Are you also going to merge #153 ?

**Comment by raveit65** [comment]
merged
https://github.com/mate-desktop/mate-utils/commit/8c19823f0b4d6fce9676bc6cdca4bb2edf44ce58
https://github.com/mate-desktop/mate-utils/commit/26a3d2bc96278d43fdb913c1b3430cd9be4c4663
https://github.com/mate-desktop/mate-utils/commit/30c99286eda160f95fd7f17ba4e82e2e368fc6eb
https://github.com/mate-desktop/mate-utils/commit/a51ba606493956946e7ca25b595c84bce69c2994

Thank you

And yes will test now #153

**Comment by monsta** [comment]
Well, screenshot dialog (```mate-screenshot -i```) is kind of broken with GTK+ 3.20 now...

broken

For comparison - GTK+2 version:

unbroken

**Comment by raveit65** [comment]
oh, the effect GtkComboBox and the checkbox is missing.
@oz123 
Can you please take look into the glade file?
Looks like i merged it to early.

**Comment by raveit65** [comment]
and it looks like that the stock icon replacement does not work.
https://github.com/mate-desktop/mate-utils/pull/152/commits/8c9f85c893ff81c6dbba3d27d8ef9151516d6f99

**Comment by oz123** [comment]
OK. It seems that I erased something which was not supposed to be erased. However, from a quick look, it seems to me that glade UI is not responsible for that. I'll take a deeper look. 

What do you mean with "stock icon replacement does not work?"

**Comment by oz123** [comment]
The difference in look is because I removed the gtk_alignment (which trimmed the dialog to the left and to the bottom, it's wrong, but it's not about the icon...). Here is a patch that reverts it, and fixed it.

[0001-Revert-removal-of-gtk_alignment.patch.txt](https://github.com/mate-desktop/mate-utils/files/328605/0001-Revert-removal-of-gtk_alignment.patch.txt)

**Pull request closed without merging**
