### PR TITLE
Gettext

### PR DESCRIPTION
**Pull request by yetist**
Migrate from intltools to gettext.
NOTE:  I disabled ru.po and uk.po, they has errors when building.

### CODE REVIEW

**Comment by monsta** [comment]
>  NOTE: I disabled ru.po and uk.po, they has errors when building.

Oh, not again... I'll have a look.

**Comment by monsta** [comment]
Same old story...

`mate-dictionary/src/gdict-window.c`
```C
  if (count == 0)
    message = g_strdup (_("No definitions found"));
  else
    message = g_strdup_printf (ngettext("A definition found",
					"%d definitions found",
					count),
		    	       count);
```

@sc0w: I forgot how you fixed similar issues without changing the code... uploaded modified `.po` file to Transifex?

**Comment by rbuj** [comment]
ru.po: Russian (msgstr[0]: one, msgstr[1]: few, msgstr[2]: many, msgstr[3]: other)
```
 msgstr[0] "Найдено определение"
 msgstr[1] "Найдено %d определения"
 msgstr[2] "Найдено %d определений"
 msgstr[3] "Найдено %d определение"
```
missing `%d` in `msgstr[0]`

**Comment by rbuj** [comment]
uk: same issue
```
msgstr[0] "знайдено визначення"
msgstr[1] "%d знайдено визначення"
msgstr[2] "%d знайдено визначень"
msgstr[3] "%d знайдено визначень"
```
missing `%d` in `msgstr[0]`

**Comment by sc0w** [comment]
@mate-desktop/core-team 

seems I don''t have permissions, but we can solve the problem changing the check here:

https://docs.transifex.com/translation-checks/setting-translation-checks

who can do the job?

**Comment by raveit65** [comment]
I can't edit `organization settings`.
A single fixed *.mo file can be uploaded by an admin.
Bildschirmfoto zu 2019-12-26 16-36-22

**Comment by sc0w** [comment]
@monsta 



@yetist I think the languages are fixed with https://github.com/mate-desktop/mate-utils/commit/0568d8eeb506deff95f100b4ba55508b74e44542 , you can remove https://github.com/mate-desktop/mate-utils/pull/256/commits/efc6be72e8df83ed6ad162e1d1e638a30aa696f8 and rebase against master

@raveit65 we need to change the check to avoid more problems in the future, and the translations can be fixed by translators easily, I think we need to change this check

Screenshot-2019-12-10-at-10-16-22

@raveit65 btw, offtopic, can you add @yetist to Maintainers at transifex?

**Comment by raveit65** [comment]
@sc0w 
I agree with you to change that, but i don't have access to this page. 
according to this link https://docs.transifex.com/translation-checks/setting-translation-checks
it is under `organization settings`. I think only the owner of Mate at transifex can do that.
I have a feeling that this is @stefano-k

**Comment by sc0w** [comment]
@yetist  the patch for debian in travis can be disabled?

**Comment by yetist** [comment]
> @yetist the patch for debian in travis can be disabled?

Yes, done.

**Comment by sc0w** [comment]
@raveit65 why portuguese is disabled in searchtool in travis since the commit https://github.com/mate-desktop/mate-utils/commit/1ee9d61c613c17a8272c042fc40d8dc063e3f1d2 ?

**Comment by raveit65** [comment]
Not a really new issue, sometimes building failed because of Portuguese language.
https://github.com/mate-desktop/mate-utils/issues/210#issuecomment-459828773

**Comment by sc0w** [comment]
@raveit65 

> I agree with you to change that, but i don't have access to this page.

The problem was solved, the settings was changed by https://www.transifex.com/user/profile/mauron/

:)

**Pull request merged**
