### PR TITLE
dictionary: Do not use 'gtk_button_clicked' to emit 'clicked' signal

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by raveit65** [comment]
Seems a simple change, only for understanding.....
What is the reason to do that?

**Comment by rbuj** [comment]
Now it checks that the signal is connected to a handler, before emitting it.

https://github.com/GNOME/glib/blob/b108072d9ef24dc825f2faafeb4d4ae7ae616967/gobject/gsignal.c#L3528-L3597
https://github.com/GNOME/gtk/blob/b933d576322b716ede78a89b97189c4198437286/gtk/gtkbutton.c#L1530-L1542

**Comment by vkareh** [comment]
I think you might be referring to `g_signal_emitv`, rather than `g_signal_emit`. Notice that both functions "reset the return value to the default if no handlers are connected". Ultimately they both call `g_signal_emit_valist`, but the second one needs to do parsing of the signal name. Apart from that they are the same. I think this PR adds unnecessary complexity.

**Comment by rbuj** [comment]
Ok, no problem, I closed it. I saw that it was removed from the gtk examples and from the codebase on master branch.

**Pull request closed without merging**
