### PR TITLE
don't use deprecated gtk_show_uri

### PR DESCRIPTION
**Pull request by raveit65**
Please test.

### CODE REVIEW

**Comment by raveit65** [comment]
I split out fix for gdict-applet because it causes a redraw issue for the applet.
Sadly, i see that with other applets lick clock or wncklist or workspace-switcher too.
So i let it here in the PR and ask for help to fix it.
To reproduce:
1. Choose a theme which styles a applet buuton for for hover and selected state, ie. Blue-Submarine.
2. select help from applet menu and close yelp after running
3. hover with the mouse over the applet
Now the applet bg change to the hover-state color from theme but it doesnt go back to normal color after this.
Hope this is understandable :-)
... and someone have an idea to fix the deprecation commit.
Otherwise i've no idea fix this deprecation for all applets.

**Comment by lukefromdc** [comment]
The applet redraw issue also makes the applet unresponsive to changing the theme. Apparently, once yelp has been called from it and closed, the next change of style is the last one rendered. From that point until the panel is restarted the applet still responds to everything else, but the button remains rendered as it was with the last change of appearance, whether this be a hover state, a checked state, a theme change, whatever. It is a generalized redrawing issue. Any chance this is GTK 3.22 only?

My version of Yelp won't run with GTK 3.20 or earlier so I can't easily test this with different GTK versions, but my suspicion is we have something in libmate-panel-applet that does not like  gtk_show_uri . We've got panel-show.c, which is listed as "a helper around gtk_show_uri" in libpanel-util, wonder if the problem is in there?

**Comment by raveit65** [comment]
I stumbled also about panel-show.c and i agree with you. Here every function use GtkScreen and not GtkWindow which is needed for gtk_show_uri_on_window.
I have the feeling that a complete rewrite of panel-show.c is needed to fix that deprecation for the panel and applets.
In case of gdict-applet it's only a bg which doesn't change anymore, but with wnck-applets or clock it's even more worse if you use gtk_show_uri_on_window.
I will hold on every PR/commit for applets until we know what's going on.
Help is appreciated.

**Comment by raveit65** [comment]
Btw.  gtk_show_uri_on_window started with gtk+-3.22 in result we can't test this with earlier gtk+

**Comment by lukefromdc** [comment]
First place to look for a fix is to see if gnome-panel did anything about this

**Comment by raveit65** [comment]
I did, but here we're standing at the frontline.
.... no deprecatinfixes for gtk_show_uri there.

**Comment by lukefromdc** [comment]
GNOME has panel-show.c in gnome-panel, even in version 3.25.  It has not been updated in 3 years-but it does have gtk-show-uri, thanks to this commit from 2008 that is surely also in mate-panel as well:

https://github.com/mate-desktop/mate-utils/pull/173#issuecomment-318752486

I'm going to play with this a bit, will test the usual deprecation fix in panel-show.c and see what happens.

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/mate-panel/pull/627 switches panel-show.c and the applets in mate-panel over to gtk_show_uri_on_window,  created no new problems, but also had exactly no effect on the ugly mess with the dictionary applet.

**Comment by raveit65** [comment]
Using NULL here fixes the redraw issue with gdict-applet.
Please test again.

**Comment by lukefromdc** [comment]
That fixes it, the dictionary applet redraw issues are gone, and help works fine in all of these

**Pull request merged**
