### PR TITLE
mate-screenshot: added New button

### PR DESCRIPTION
**Pull request by tbighetti**
I need to capture numerous screenshots or reselect the area. For this I needed to be constantly opening and closing the mate-screenshot application. I made this improvement to increase my productivity.
Any questions I am available.
Best regards

image

### CODE REVIEW

**Comment by raveit65** [comment]
nice idea :)

**Comment by lukefromdc** [comment]
I will test this once the build warnings are fixed. I like this feature, it's one I expect to make use of a lot.

**Comment by lukefromdc** [comment]
I was able to fix the build warnings with this patch:
```

122,123d121
< void loop_dialog_screenshot ();
< 
1266c1264
< loop_dialog_screenshot ()
---
> loop_dialog_screenshot (void)
1282c1280
<           return;
---
>           return EXIT_SUCCESS;


```

**Comment by tbighetti** [comment]
Thanks @raveit65 and @lukefromdc , I just applied the fix build warnings.

**Comment by monsta** [comment]
Maybe I don't know something, but... how to use it? If I press Save button, current screenshot is saved, the dialog is closed. If I press New button, current screenshot is lost, the dialog is closed, and I get the interactive screenshot dialog. What does it actually add?

**Comment by tbighetti** [comment]
In my case, I use the "Copy to clipboard" button a lot. I develop manuals and respond emails with screenshots. In this case the functionality would be to good advantage.

I also think that this new feature has no functionality for when the user saves the image. In this case I suggest that when saving identify if it is in interactive mode and not close the dialog, only display an alert saying that the file has been saved. What do you think?

**Comment by raveit65** [comment]
Thanks

**Comment by raveit65** [comment]
I merge this because we're tomorrow in freeze for 1.20 release and avoid to wait whole next development cycle to see this implementation in stable branch.
Maybe this can be improved?
For me pressing the **NEW** button should save to old screenshot or a popup to ask for this should come up before the new interactive dialog displays again.

**Pull request merged**
