### PR TITLE
logview: Rewrite logview-filter.ui from scratch

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by cwendling** [comment]
I couldn't test yet, but I agree the second screenshot is clearly better for the color picker part: it's a lot clearer to me what's happening, and I think it looks better :+1:
However, I think the padding around the whole dialog should be restored, here labels on the left are too close to the window border IMO (and I think the HIG suggest the same).

**Comment by rbuj** [comment]
@cwendling done

**Comment by raveit65** [comment]
I can confirm that edges are better now.
Bildschirmfoto zu 2020-03-10 15-25-13
@cwendling 
Any other concerns?

**Comment by cwendling** [comment]
Yep, borders are better now :+1:

**Comment by raveit65** [comment]
offtopic on:
Under fedora 32 the UI for query the password is gone.
FRom a terminal i get this query:
```
[rave@f32 ~]$ mate-system-log 
You are attempting to run "mate-system-log" which may benefit from administrative
privileges, but more information is needed in order to do so.
Authenticating as "root"
Password: 
[rave@f32 ~]$ 
```
Normally it is a gtk2 UI 
passwort-abfrage

Does anyone have an idea from which application this gtk2 password query UI is?
offtopic off

**Comment by rbuj** [comment]
@raveit65 I recall it's Fedora usermode.

**Comment by raveit65** [comment]
yep, it's usermode.
But usermode-gtk is missing in default installation. Looks like it is dropped from a `comps` group for fedora 32.
Than i need usermode-gtk to MATE group in `comps`, good...problem fixed :)

**Pull request merged**
