### PR TITLE
mdict: fix some gtk+3 deprecations and a few improvements

### PR DESCRIPTION
**Pull request by raveit65**
- 2 little but fine improvements for both toolkit versions, see links in commit message
- started with fixing deprecations for gtk+3, especial the last commit needs a review.

@flexiondotorg @monsta @lukefromdc @clefebvre 
Please test and review.

### CODE REVIEW

**Comment by raveit65** [comment]
Btw. I'm not sure if this is an API change as mentioned in commit messages (from origin)
But upstream dev thinks it is.

**Comment by lukefromdc** [comment]
A quick test of all the binaries built didn't reveal any problems on this end,
though I'm probably not fully aware of all the ways to use the dictionary

**Comment by monsta** [comment]
The mentioned API changes are migrations from GtkVBox to GtkBox which were already done here some time ago :smile:

**Comment by monsta** [comment]
Works fine with 3.20. I'm not sure about "HACK" with hardcoding color values in the last commit, but if you don't see any theme-related issues, then I'm fine with it.

**Pull request merged**
