### PR TITLE
port to GtkGrid

### PR DESCRIPTION
**Pull request by raveit65**
Please test and review.
@lukefromdc 
Hope this fixes the issue with gtk+-3.21, couldn't reproduce the issue as the offending gtk+ commit isn't released and in f25.

### CODE REVIEW

**Comment by lukefromdc** [comment]
I'll try these out when I get home this afternoon

**Comment by lukefromdc** [comment]
Works better than what I did as the entry now resizes to whatever a
user sets as the desired width for mate-search-tool. This fixes the 
mate-search-tool problem and everything else worked (I tested them all)

Perhaps a branch and PR for gnome-search-tool are in order here too?

**Comment by raveit65** [comment]
gnome-utils is archived at gnome git and gnome-shell use a own search, but feel free to do a PR there.
Or do you need a commit for your own use?

**Comment by lukefromdc** [comment]
The old version of gnome-search-tool still works fine, no idea why it does.
I would assume the developers of gnome-session-flashback need it, and
that these deprecations could cause them problems in the future. 

It is still provided by Debian and presumably many distros since it still
works, Debians is version 3.6-2, with GNOME seven releases past
that. I guess GNOME no longer maintains it but at least does keep
the code available, which is all we can expect if they no longer have
a use for it themselves. Not sure what they'd do with a PR given that.

**Pull request merged**
