### PR TITLE
Add WARN_CFLAGS to CFLAGS

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by raveit65** [comment]
I just added the travis config, same what we did for engrampa.

**Comment by rbuj** [comment]
@raveit65 I think that MAINTAINER_CFLAGS is an obsolete variable for now, and it should be removed.

**Comment by raveit65** [comment]
@rbuj 

> I think that MAINTAINER_CFLAGS is an obsolete variable for now, and it should be removed.

Yes, i think so.

**Comment by rbuj** [comment]
> > I think that MAINTAINER_CFLAGS is an obsolete variable for now, and it should be removed.
> 
> Yes, i think so.

PR https://github.com/mate-desktop/mate-utils/pull/251

**Pull request merged**
