### PR TITLE
logview: i18n date format in side pane

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by lukefromdc** [comment]
I really can't test this for function due to having no other languages installed but I'm thinking to see it in action would have to wait for the next round of translations anyway.  Thus we just need someone to confirm this is what transifex needs. The `_()` outside the quotes in these strings worked fine in the xrandr applet's popup menu so I don't see any trouble coming from this

**Comment by raveit65** [comment]
```
       %A     The full name of the day of the week according  to  the  current
              locale.  (Calculated from tm_wday.)

       %b     The  abbreviated  month  name  according  to the current locale.
              (Calculated from tm_mon.)

       %e     Like %d, the day of the month as a decimal number, but a leading
              zero is replaced by a space. (SU) (Calculated from tm_mday.)
```
I don't get what a translator should translate here?
```
msgid "%A, %e %b"
msgstr ""
```
So, msgstr should be the same as msgid?

**Comment by rbuj** [comment]
strftime & ICU notation equivalence:
- %A = EEEE
- %b = MMM
- %e = d
- "%A, %e %b" = "EEEE, d MMM"

Sample code to check if msgstr should be the same as msgid using [ICU](https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_74/apis/icu.htm):
- https://github.com/rbuj/icutest

Output:
```
[ca] [EEEE, d MMM] [dilluns, 29 de jul.]
[fr] [EEEE d MMM] [lundi 29 juil.]
[de] [EEEE, d. MMM] [Montag, 29. Juli]
[ja] [M月d日EEEE] [7月29日月曜日]
```
In this case msgstr is not always equal to msgid.

**Comment by raveit65** [comment]
Yes, i know that a date is writen different with different languages.
That wasn't my questions.
But what should a translator write in `msgstr` for this string?

**Comment by rbuj** [comment]
The date representation in strftime() format, which may include the fields: month, day, weekday. Those fields can be abbreviated to reduce the length of the translated date. You can test your format pattern using date command:

## Example
### English

Not abbreviated date without year:
$ LANG=C date +"%A, %B %e"
Monday, July 29

Abbreviated date without year:
$ LANG=C date +"%a, %b %e"
Mon, Jul 29

### Catalan
http://www.unicode.org/cldr/charts/28/verify/dates/ca.html

Not abbreviated date without year:
$ LANG=ca_ES date +"%A, %e %B"
dilluns, 29 de juliol

Abbreviated date without year:
$ LANG=ca_ES date +"%a %e %b"
dl. 29 de jul.

**Comment by raveit65** [comment]
I don't want to know a terminal output.
Just show me how it looks in .mo file for eg. your language.
```
msgid "%A, %e %b"
msgstr "want you want to write here for ca language?"
```

**Comment by rbuj** [comment]
```shell
$ grep -A 1 "%A, %e %b" po/ca.po 
msgid "%A, %e %b"
msgstr "%a %e %b"
```

Before

Captura de pantalla a 2019-07-29 17-13-19

After

Captura de pantalla a 2019-07-29 17-16-09

**Comment by raveit65** [comment]
```shell
$ grep -A 1 "%A, %e %b" po/ca.po 
msgid "%A, %e %b"
msgstr "%a %e %b"
```
Thanks for simply answering my question.
So, this is different for most languages.
Do you really think all translator knows this differences?
I expect issues by translator with this string.
Any way, let see what happens.

**Comment by rbuj** [comment]
I think that most translators are familiarized with strftime. For instance, several strftime format strings already exist in mate-panel.

https://github.com/mate-desktop/mate-panel/blob/60c14740efc90306707987907d26912adb7ef76a/mate-panel.pot#L144-L148

**Pull request merged**
