### PR TITLE
help: update figures of baobab

### PR DESCRIPTION
**Pull request by selectiveduplicate**
Update four figures of baobab in help pages.

### CODE REVIEW

**Comment by sc0w** [comment]
we can see here one issue with Traditional OK...



... the white line in the title.

I noticed it since one update in my system and with the same mate-themes version. The look is ok in the past with the same mate-themes version.

**Comment by selectiveduplicate** [comment]
> we can see here one issue with Traditional OK...
> 
> 
> 
> ... the white line in the title.
> 
> I noticed it since one update in my system and with the same mate-themes version. The look is ok in the past with the same mate-themes version.

Yeah that line is materialised with that theme, which I've been currently using. I didn't notice whether the line was there in previous versions. The theme is very much similar to the Fedora theme I saw in the old Fedora 14 but there wasn't any white lines there. If it's required, I can take the pictures again with BlueMenta theme.

**Comment by rbuj** [comment]
https://github.com/mate-desktop/mate-themes/pull/271 should fix your screenshots :)

**Comment by raveit65** [comment]
I am still wondering that i don't see the glitches when using TOK themes.

**Comment by selectiveduplicate** [comment]
@rbuj Please check.

**Pull request merged**
