### PR TITLE
Make inkscape and rsvg-convert optional

### LINKED ISSUE #223: [configure option for compiling mate-utils] make inkscape optional (for mate-utils-1.22.2 or later)
Hello mate-desktop developers,

Today I tried to compile mate-utils from source:

https://pub.mate-desktop.org/releases/1.22/mate-utils-1.22.1.tar.xz

This was the URL I was using.

I can not get past the configure stage. The configure stage, with
a classical ./configure --prefix=/usr, reports this **error**:

checking for glib-genmarshal... /System/Index/bin//glib-genmarshal
checking for glib-mkenums... /System/Index/bin//glib-mkenums
checking for rsvg-convert... /System/Index/bin//rsvg-convert
checking for inkscape... no
**configure: error: could not locate inkscape**

I can not get inkscape to compile on my current setup due to another
problem, so I would like to suggest to make inkscape optional, unless
it is really mandatory. 

I looked at the README and found no mention of inkscape:

        intltool                 >= 0.50.1
        mate-common              >= 1.10.0
        glib                     >= 2.36.0
        gio                      >= 2.36.0
        gtk+                     >= 3.14.0
        libmate-panel-applet     >= 1.17.0
        libgtop                  >= 2.12.0
        libcanberra-gtk          >= 0.4

I assume that inkscape is probably only necessary for e. g.
mate-screenshot or something like that; but I am fine with
getting the other things to compile if that would be possible.

Right now I can not get anything to compile due to inkscape
being checked and not found.

I would like to suggest an option:

    --disable-inkscape

And perhaps a notification on the commandline, that this
will prevent installing xyz or whatever depends on inkscape
(although I can not imagine too much to depend on inkscape; 
to be honest, it confuses me that there is a dependency on
inkscape. It seems a bit counter-intuitive to me. Has this been
added recently? I could swear I could compile mate-utils,
the version before, just fine without inkscape. But anyway,
I am just reporting the problem - I am sure an appropriate
course can be picked by the mate-desktop team. Thanks
for a great DE!)

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/73280279-configure-option-for-compiling-mate-utils-make-inkscape-optional-for-mate-utils-1-22-2-or-later?utm_campaign=plugin&utm_content=tracker%2F1509859&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1509859&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by rbuj**
TEST on Fedora:
inkscape, librsvg2-tools package are not installed on system: The user can build, install and distribute the package:
```shell
  $ sudo dnf remove inkscape librsvg2-tools -y
  $ ./configure --prefix=/usr
  $ make
  $ sudo make install
  $ make distcheck
```

logview/data/icons:

Can not run build-png-icons target if inkscape package is not installed on system:
```shell
  $ make -C logview/data/icons clean-png-icons
make: Entering directory '/home/robert/devel/mate-utils/logview/data/icons'
rm -f hicolor_apps_16x16_mate-system-log.png hicolor_apps_22x22_mate-system-log.png hicolor_apps_32x32_mate-system-log.png hicolor_apps_48x48_mate-system-log.png hicolor_apps_256x256_mate-system-log.png 
make: Leaving directory '/home/robert/devel/mate-utils/logview/data/icons'
  $ make -C logview/data/icons build-png-icons
make: Entering directory '/home/robert/devel/mate-utils/logview/data/icons'
make: *** No rule to make target 'hicolor_apps_16x16_mate-system-log.png', needed by 'build-png-icons'.  Stop.
make: Leaving directory '/home/robert/devel/mate-utils/logview/data/icons'
```
Can run build-png-icons target if inkscape package is installed on system:
```shell
  $ sudo dnf install inkscape -y
  $ ./configure --prefix=/usr
  $ make -C logview/data/icons build-png-icons
make: Entering directory '/home/robert/devel/mate-utils/logview/data/icons'
Background RRGGBBAA: ffffff00 Area 303:65:319:81 exported to 16 x 16 pixels (96 dpi) Bitmap saved as: hicolor_apps_16x16_mate-system-log.png
Background RRGGBBAA: ffffff00 Area 303:101:325:123 exported to 22 x 22 pixels (96 dpi) Bitmap saved as: hicolor_apps_22x22_mate-system-log.png
Background RRGGBBAA: ffffff00 Area 304:142:336:174 exported to 32 x 32 pixels (96 dpi) Bitmap saved as: hicolor_apps_32x32_mate-system-log.png
Background RRGGBBAA: ffffff00 Area 296:202:344:250 exported to 48 x 48 pixels (96 dpi) Bitmap saved as: hicolor_apps_48x48_mate-system-log.png
Background RRGGBBAA: ffffff00 Area 33:11:289:267 exported to 256 x 256 pixels (96 dpi) Bitmap saved as: hicolor_apps_256x256_mate-system-log.png
make: Nothing to be done for 'build-png-icons'.
make: Leaving directory '/home/robert/devel/mate-utils/logview/data/icons'
-
```

baobab/pixmaps:

Can not run build-png-icons target if librsvg2-tools package is not installed on system:
```shell
  $ make -C baobab/pixmaps clean-png-icons
make: Entering directory '/home/robert/devel/mate-utils/baobab/pixmaps'
rm -f hicolor_apps_16x16_mate-disk-usage-analyzer.png hicolor_apps_22x22_mate-disk-usage-analyzer.png hicolor_apps_32x32_mate-disk-usage-analyzer.png hicolor_apps_48x48_mate-disk-usage-analyzer.png hicolor_apps_128x128_mate-disk-usage-analyzer.png 
make: Leaving directory '/home/robert/devel/mate-utils/baobab/pixmaps'
  $ make -C baobab/pixmaps build-png-icons
make: Entering directory '/home/robert/devel/mate-utils/baobab/pixmaps'
make: *** No rule to make target 'hicolor_apps_16x16_mate-disk-usage-analyzer.png', needed by 'build-png-icons'.  Stop.
make: Leaving directory '/home/robert/devel/mate-utils/baobab/pixmaps'
```
Can run build-png-icons target if librsvg2-tools package is installed on system:
```shell
  $ sudo dnf install -y librsvg2-tools
  $ ./configure --prefix=/usr
  $ make -C baobab/pixmaps build-png-icons
make: Entering directory '/home/robert/devel/mate-utils/baobab/pixmaps'
/usr/bin/rsvg-convert -w 16 -h 16 hicolor_apps_scalable_mate-disk-usage-analyzer.svg -o hicolor_apps_16x16_mate-disk-usage-analyzer.png
/usr/bin/rsvg-convert -w 22 -h 22 hicolor_apps_scalable_mate-disk-usage-analyzer.svg -o hicolor_apps_22x22_mate-disk-usage-analyzer.png
/usr/bin/rsvg-convert -w 32 -h 32 hicolor_apps_scalable_mate-disk-usage-analyzer.svg -o hicolor_apps_32x32_mate-disk-usage-analyzer.png
/usr/bin/rsvg-convert -w 48 -h 48 hicolor_apps_scalable_mate-disk-usage-analyzer.svg -o hicolor_apps_48x48_mate-disk-usage-analyzer.png
/usr/bin/rsvg-convert -w 128 -h 128 hicolor_apps_scalable_mate-disk-usage-analyzer.svg -o hicolor_apps_128x128_mate-disk-usage-analyzer.png
make: Leaving directory '/home/robert/devel/mate-utils/baobab/pixmaps'
```

Closes #223

### CODE REVIEW

**Comment by rbuj** [comment]
It also checks if inkscape binary file exists.

**Comment by sc0w** [comment]
with this change can librsvg to be optional too?

**Comment by rbuj** [comment]
@sc0w done

**Comment by sc0w** [comment]
@rbuj question: we need now `inkscape` and `librsvg` in `travis.yml `or it can be removed?

**Comment by flexiondotorg** [comment]
@rbuj What is the side affect of not having inkscape or rsvg-convert available at build time?

**Comment by rbuj** [comment]
@flexiondotorg `make distcheck` fails, even if EXTRA_DIST contains png files.

**Comment by rbuj** [comment]
I think that it's fixed now

**Comment by sc0w** [comment]
@rbuj `librsvg` can be removed in arch in `travis.yml` too?

https://github.com/mate-desktop/mate-utils/pull/228/files#diff-354f30a63fb0907d4ad57269548329e3R74

**Comment by rbuj** [comment]
@sc0w done

**Comment by raveit65** [comment]
Any chance to squash that in one or two commits?

**Comment by rbuj** [comment]
All can be squashed in one commit, PR description updated.

**Comment by rbuj** [comment]
@raveit65 done

**Comment by raveit65** [comment]
@flexiondotorg 
For fedora i compile it simply with inkscape and librsvg. It is only a build require which doesn't pull in inkscape in an installation.
I tested  this before i merged previous PR.

**Pull request merged**
