### PR TITLE
gdict-pref-dialog: Simplify notebook scroll event

### PR DESCRIPTION
**Pull request by rbuj**
Based on:
- https://github.com/mate-desktop/mate-terminal/commit/8d2eb0898154f2624e2ae34039169f307a3411a5
- https://github.com/mate-desktop/mate-terminal/commit/622e2d1272bf2d7a99d147482ae6a51b0a77f188

### CODE REVIEW

**Comment by tamplan** [comment]
Indent?

**Comment by rbuj** [comment]
What indent?

**Comment by tamplan** [comment]
> What indent?

It seems to be 2 spaces and not 4 spaces if i read file changes on github.

**Comment by rbuj** [comment]
This file uses 2 spaces for indent.

**Comment by tamplan** [comment]
Ok, when a file use 2 spaces, you use 2 spaces too, good to know, thanks.

**Pull request merged**
